#!/bin/bash
#
# Script to run docker cinder-controller container.
#
set -x
set -e

# Check for Root user
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root or with sudo"
    exit 1
fi

# Configure the cinder-controller image name
export IMAGE_NAME="${IMAGE_NAME:-cinder-controller}"

# Configure the cinder-controller container name
export CONTAINER_NAME="${CONTAINER_NAME:-cinder-controller}"

# Configure the cinder-controller Hostname
export CINDER_CONTROLLER_HOSTNAME="${CINDER_CONTROLLER_HOSTNAME:-$HOSTNAME}"

# Configure the cinder-controller container DNS search order.
export DNS_SEARCH="${DNS_SEARCH:-example.com}"

docker run --privileged -d -h $CINDER_CONTROLLER_HOSTNAME --dns-search $DNS_SEARCH -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 8776:8776 --name="$CONTAINER_NAME" $IMAGE_NAME

# Get the PID of the cinder-controller container
CONTAINER_PID="$(docker inspect --format={{.State.Pid}} $CONTAINER_NAME)"

#Use nsenter to enter the namespaces of the running cinder-controller container.
nsenter -m -u -n -i -p -t $CONTAINER_PID /bin/bash

exit $?
